[logging]
# One of DEBUG, INFO, WARNING, ERROR
level = INFO

[idmefv2]
# The IDMEFv2 server URL (required)
url = http://testserver.idmefv2:9911

[samhain]
# Path to the Samhain log file to monitor
logfile = /var/log/samhain/samhain.log
