
include:
  - ../elastic+filebeat+sshd/docker-compose.yml
  - ../testserver/docker-compose.yml

services:
  elastalert:
    depends_on:
      es01:
        condition: service_healthy
    build:
       context: ./containers/elastalert
    volumes:
      - type: "bind"
        source: "./storage/elastalert/config.yaml"
        target: "/opt/elastalert/config.yaml"
      - type: "bind"
        source: "./storage/elastalert/rules"
        target: "/opt/elastalert/rules"
      - type: "bind"
        source: "${IDMEFV2_CONNECTORS_GIT}"
        target: "/idmefv2-connectors"
